"""alter teble usuario correo unique

Revision ID: 0a337da82e94
Revises: 825548157ed7
Create Date: 2026-03-24 13:42:47.626867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a337da82e94'
down_revision: Union[str, Sequence[str], None] = '825548157ed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'usuario', ['correo'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario', type_='unique')
    # ### end Alembic commands ###
