"""create table factura

Revision ID: 22d84de3635a
Revises: 919d1262112b
Create Date: 2026-03-24 14:18:13.176041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22d84de3635a'
down_revision: Union[str, Sequence[str], None] = '919d1262112b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factura',
    sa.Column('id_factura', sa.String(length=80), nullable=False),
    sa.Column('fecha_factura', sa.Date(), nullable=False),
    sa.Column('nombre_empresa', sa.String(length=200), nullable=False),
    sa.Column('costo_total', sa.Double(), nullable=False),
    sa.Column('fk_placavehiculo', sa.String(length=6), nullable=False),
    sa.ForeignKeyConstraint(['fk_placavehiculo'], ['vehiculo.placa'], ),
    sa.PrimaryKeyConstraint('id_factura')
    )
    op.create_index(op.f('ix_factura_id_factura'), 'factura', ['id_factura'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_factura_id_factura'), table_name='factura')
    op.drop_table('factura')
    # ### end Alembic commands ###
