"""alter table usuarios add column contrasena

Revision ID: 78c9d078a13d
Revises: 9dae10319778
Create Date: 2026-03-30 14:26:40.274750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78c9d078a13d'
down_revision: Union[str, Sequence[str], None] = '9dae10319778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('contrasena', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'contrasena')
    # ### end Alembic commands ###
