"""alter table factura url_factura

Revision ID: 7a5a4a79b72e
Revises: 9fe8d6d14dd3
Create Date: 2026-03-24 15:00:21.385848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a5a4a79b72e'
down_revision: Union[str, Sequence[str], None] = '9fe8d6d14dd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('factura', sa.Column('url_factura', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('factura', 'url_factura')
    # ### end Alembic commands ###
