"""create table vehiculo

Revision ID: 825548157ed7
Revises: 8ebe67bbe25d
Create Date: 2026-03-24 13:40:18.579312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '825548157ed7'
down_revision: Union[str, Sequence[str], None] = '8ebe67bbe25d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehiculo',
    sa.Column('placa', sa.String(length=6), nullable=False),
    sa.Column('cilindraje', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('placa')
    )
    op.create_index(op.f('ix_vehiculo_placa'), 'vehiculo', ['placa'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehiculo_placa'), table_name='vehiculo')
    op.drop_table('vehiculo')
    # ### end Alembic commands ###
