"""primera migracion

Revision ID: 84214a8a8dfb
Revises: 
Create Date: 2026-03-20 17:27:10.889256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84214a8a8dfb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('documento_identidad', sa.BigInteger(), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('rol', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('documento_identidad')
    )
    op.create_index(op.f('ix_usuario_documento_identidad'), 'usuario', ['documento_identidad'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuario_documento_identidad'), table_name='usuario')
    op.drop_table('usuario')
    # ### end Alembic commands ###
