"""ater table usuario fecha_registro

Revision ID: 8ebe67bbe25d
Revises: 84214a8a8dfb
Create Date: 2026-03-24 13:29:06.161481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ebe67bbe25d'
down_revision: Union[str, Sequence[str], None] = '84214a8a8dfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('fecha_registro', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'fecha_registro')
    # ### end Alembic commands ###
