"""create table tarjeta_propiedad

Revision ID: 919d1262112b
Revises: 5769c4e595ba
Create Date: 2026-03-24 14:07:30.095462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '919d1262112b'
down_revision: Union[str, Sequence[str], None] = '5769c4e595ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarjetapropiedad',
    sa.Column('numero_tarjeta', sa.BigInteger(), nullable=False),
    sa.Column('nombre_propietario', sa.String(length=250), nullable=False),
    sa.Column('cilindraje', sa.Integer(), nullable=False),
    sa.Column('documento_propietario', sa.BigInteger(), nullable=False),
    sa.Column('marca', sa.String(length=150), nullable=False),
    sa.Column('clase_vehiculo', sa.String(length=100), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=False),
    sa.Column('servicio', sa.String(length=100), nullable=False),
    sa.Column('tipo_carroceria', sa.String(length=100), nullable=False),
    sa.Column('linea_vehiculo', sa.String(length=100), nullable=False),
    sa.Column('numero_motor', sa.BigInteger(), nullable=False),
    sa.Column('combustible', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=100), nullable=False),
    sa.Column('placa', sa.String(length=6), nullable=False),
    sa.Column('fk_placavehiculo', sa.String(length=6), nullable=False),
    sa.ForeignKeyConstraint(['fk_placavehiculo'], ['vehiculo.placa'], ),
    sa.PrimaryKeyConstraint('numero_tarjeta')
    )
    op.create_index(op.f('ix_tarjetapropiedad_numero_tarjeta'), 'tarjetapropiedad', ['numero_tarjeta'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tarjetapropiedad_numero_tarjeta'), table_name='tarjetapropiedad')
    op.drop_table('tarjetapropiedad')
    # ### end Alembic commands ###
