"""create table servicio

Revision ID: 9fe8d6d14dd3
Revises: 22d84de3635a
Create Date: 2026-03-24 14:59:23.155121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fe8d6d14dd3'
down_revision: Union[str, Sequence[str], None] = '22d84de3635a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servicio',
    sa.Column('id_servicio', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('costo', sa.Double(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('fk_idfactura', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['fk_idfactura'], ['factura.id_factura'], ),
    sa.PrimaryKeyConstraint('id_servicio')
    )
    op.create_index(op.f('ix_servicio_id_servicio'), 'servicio', ['id_servicio'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_servicio_id_servicio'), table_name='servicio')
    op.drop_table('servicio')
    # ### end Alembic commands ###
